name: Descompactar e Compilar DLL

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Baixar código do repositório
      uses: actions/checkout@v4

    - name: Descompactar o arquivo ZIP
      shell: powershell
      run: Expand-Archive -Path "Assembly-CSharp.zip" -DestinationPath "projeto_extraido" -Force

    - name: Configurar .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'

    - name: Compilar o projeto
      shell: powershell
      run: |
        cd projeto_extraido
        dotnet build --configuration Release

    - name: Salvar a DLL gerada
      uses: actions/upload-artifact@v4
      with:
        name: minha-dll-final
        path: '**/bin/Release/**/*.dll'
